name: ci

on:
  push:
    branches: ["main"]
  pull_request:
    types: ["opened", "synchronize"]
  workflow_dispatch:

jobs:
  lint-and-type-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.8.15"
          enable-cache: true

      - name: Lint and type check
        run: uv run bash scripts/lint.sh